name = "spinmachocasino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachocasino.com.pt"
HMAC_KEY = "5ac3a5bfe94f8aa5ee3d321a88744ddcfc4a3bc494ea7aad672e24bfec728976"
COOKIE_NAME = "8f0"
PLAY_PATH = "discover"
BUTTON_ID = "p4abcf64726574196dba2a63da6afa18a"
GATE_SALT = "fa8fcb78ed65f258"
